-- Auto-generated from schema-map-postgres.yaml (map@sha1:8C4F2BC1C4D22EE71E27B5A7968C71E32D8D884D)
-- engine: postgres
-- table:  entity_external_ids

CREATE TABLE IF NOT EXISTS entity_external_ids (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_table VARCHAR(64) NOT NULL,
  entity_pk    VARCHAR(64) NOT NULL,
  source       VARCHAR(100) NOT NULL,            -- e.g. 'rbac-repo','crm'
  external_id  VARCHAR(200) NOT NULL,
  created_at   TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_entity_external_ids UNIQUE (entity_table, entity_pk, source)
);
